#!/bin/bash


mi_usuario="combot"

# Crearemos el usuario si no existe
if id "$nuevo_usuario" &>/dev/null; then
	echo "El usuario no hizo falta crearlo porque ya existe."
else
	sudo adduser --disabled-password --gecos "" $mi_usuario
	chmod +x /usr/bin/combot.py
	
fi

pip3 install --upgrade python-telegram-bot
pip3 install python-nmap
pip3 install psutil
pip3 install ping3
pip3 install --upgrade ping3

echo "Vamos a reiniciar el servicio"

systemctl daemon-reload
systemctl restart combot.service 


exit 0
