FROM ubuntu:22.04

# Instalamos los archivos necesarios
RUN apt update \
  && apt install -y \
  bind9 \
  bind9-doc \
  dnsutils \
  nano \
  geoip-bin \
  mariadb-server \
  net-tools


# Copiamos los archivos de configuración

COPY /named.conf.options /etc/bind/
COPY /named.conf.local /etc/bind/
COPY /db.zona-pruebas.io /etc/bind/zones/

# Exponemos los puertos

EXPOSE 53/tcp
EXPOSE 53/udp
EXPOSE 953/tcp

# Arrancamos el servicio
CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]